-- Phase 10 production-readiness cleanup.
--
-- public.calculate_lead_match_score(uuid, uuid) was the Phase 6 V1 scoring
-- helper, called only from the original public.submit_project_plan(uuid)
-- body defined in the same migration (20260820032000_lead_matching.sql).
-- Phase 8 replaced submit_project_plan's body entirely
-- (20260820082001_submit_project_plan_compat.sql), routing through
-- submit_project_lead()/match_lead() instead, which score inline and
-- never call calculate_lead_match_score. Nothing in the application or
-- any other migration calls it -- it was already `revoke all ... from
-- public, anon, authenticated`, so it posed no access-control risk, but
-- it's dead code left behind in the schema. Dropping it for schema
-- hygiene ahead of launch; no behavior change.
drop function if exists public.calculate_lead_match_score(uuid, uuid);
